### ISSUE TITLE
Add a link to django-test-migrations

### ISSUE THREAD

**Issue by sobolevn** [alvassin/alembic-quickstart#1]
Hi, thanks a lot for building this example! 

I am maintaining a similar project called `django-test-migrations`: https://github.com/wemake-services/django-test-migrations

Maybe you can add a link in the readme somewhere?

**Comment by alvassin** [comment]
Honestly, I didn’t plan to make a collection of links from this repository. But if someone asks about testing django migrations - I would be glad to mention your project.

Thank you for suggestion.
